columnSuffix: wpluxhue
contentColumnType: text
fieldGroup: 17d0a86b-bb67-42f1-9695-2d7e290bb91e # Styles
handle: buttonColor
instructions: null
name: 'Button Color'
searchable: false
settings:
  default: null
  palette: Button
  setRandom: false
  useConfigFile: true
translationKeyFormat: null
translationMethod: none
type: percipiolondon\colourswatches\fields\ColourSwatches
